### ISSUE TITLE
Add to readme which PSNR, SSIM and VMAF values are considered to be good

### ISSUE THREAD

**Issue by InB4DevOps** [BassThatHertz/video-quality-metrics#12]
While I have a basic understanding on how things should be I think there should be a guide in the readme as to which values are good and which aren't.

**Comment by CrypticSignal** [comment]
Personally, I don't feel like it's worth spending my time to do this research for a few reasons:
- It's safe to assume that most people who opt to use this program to find these values are technically inclined and have at least some idea of what they're looking for. Your average person doesn't use command line programs or even know what x264 or x265 are, whereas a good portion of the users of this program are likely looking to optimise FFmpeg video encoder options for their individual preferences (Everyone has their own importance-weighting of quality/filesize/encoding time. For example, someone with a lot of storage space might be okay with a decent increase in filesize for a small increase in quality, or a person low on storage might be trying to find the lowest CRF value that they can use while not exceeding a filesize of X).

- For me, it's more about how the quality metrics obtained with different presets/CRFs **compare to one another**. Sort of like a ratio thing, e.g. "Okay, I can see that going from CRF 17 to 16, there's barely a difference in the VMAF value but the filesize difference is more substantial. Looking at the table, I like CRF value X the most as it gives me the best quality and filesize ratio for my personal preference."

- With regards to VMAF values, the link I shared in the "About the model files" section of the README contains some information about interpreting VMAF values, but I will paste it here:

_"VMAF scores range from 0 to 100, with 0 indicating the lowest quality, and 100 the highest. A good way to think about a VMAF score is to linearly map it to the human opinion scale under which condition the training scores are obtained. As an example, the default model v0.6.1 is trained using scores collected by the Absolute Category Rating (ACR) methodology using a 1080p display with viewing distance of 3H. Viewers voted the video quality on the scale of “bad”, “poor”, “fair”, “good” and “excellent”, and roughly speaking, “bad” is mapped to the VMAF scale 20 and “excellent” to 100. Thus, a VMAF score of 70 can be interpreted as a vote between “good” and “fair” by an average viewer under the 1080p and 3H condition. Another factor to consider is that the best and the worst votes a viewer can give is calibrated by the highest- and lowest-quality videos in the entire set (during training, and before the actual test starts, subjects are typically accustomed to the experiment’s scale). In the case of the default model v0.6.1, the best and the worst videos are the ones compressed at 1080p with a low quantization parameter (QP) and the ones at 240p with a high QP, respectively."_ ([source](https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12))

As this is an open-source repository, if anyone wants to add information about good SSIM/PSNR values to the README, you are free to do so.
