### ISSUE TITLE
'no transcode mode' incomplete

### ISSUE THREAD

**Issue by InB4DevOps** [BassThatHertz/video-quality-metrics#17]
cfdbe26317ec75e83349088fa759082dc3ee7047
In this commit you forgot to change `compute_metrics` to run_libvmaf.
A table must also be created.

**Comment by CrypticSignal** [comment]
I've sorted this out and I will push a new update. I'm thinking about moving the `cut_video` and `run_vmaf` functions to utils.py. What's your opinion on this? I've never made a utils.py file before and I'm not sure what kind of functions it can contain by convention. I think I like the idea of `main()` being the only function in main.py

**Comment by InB4DevOps** [comment]
In utils I’d put small functions with limited impact.
How about video_operations.py for cut_video() and run_libvmaf()?

**Comment by CrypticSignal** [comment]
I'm going to leave them in main.py, at least for now. And I'm going to delete constants.py as it's total overkill due to only containing one constant. Doing it this way doesn't save a single line in main.py either as it's just an f-string that doesn't take up more than one line.

**Comment by CrypticSignal** [comment]
`--no-transcoding-mode` has been completed in commit https://github.com/BassThatHertz/video-quality-metrics/commit/a2a984b0dedbef4559035677a7e1bd09df3cfd9c.
