### ISSUE TITLE
Apply facade pattern to main.py

### ISSUE THREAD

**Issue by InB4DevOps** [BassThatHertz/video-quality-metrics#18]
How about we create a facade for the main operations of the program 
- cut
- interval overview
- ntm
- crf comparison
- preset comparison
- something I forgot

Read here: https://refactoring.guru/design-patterns/facade

Readability will benefit greatly..

**Comment by CrypticSignal** [comment]
I'm not going to leave this "issue" open as there is no issue. Anyone who wants to improve the code should go ahead and do so, before submitting a pull request. If I like the changes, I will merge the pull request.
