### ISSUE TITLE
[2] (presets comparison mode):

### ISSUE THREAD

**Issue by MillingtonAllen** [BassThatHertz/video-quality-metrics#24]
I'm trying to compare presets.  I've tried crafting a full command manually as well as using the example from the documentation.  

[2] (presets comparison mode):
Example: python main.py -ovp original.mp4 -p medium fast faster -crf 18 -ssim -psnr

Thus I input:

allen@allen-desktop:/media/allen/2637acd8-fd84-4e6e-b830-018fc7f8703c/allen/Desktop/video-quality-metrics-master$ python3 main.py -ovp P3.mp4 -p medium fast faster -crf 18
-----------------------------------------------------------------------------------------------------------
Here's some information about the original video:
Filename: P3.mp4
Bitrate: 1018 kbit/s
Framerate: 30/1 (30.0) FPS
-----------------------------------------------------------------------------------------------------------
Presets comparison mode activated.
Presets medium, fast, faster will be compared at a CRF of 18.
-----------------------------------------------------------------------------------------------------------
Transcoding the video with preset medium...
Traceback (most recent call last):
  File "main.py", line 367, in <module>
    main()
  File "main.py", line 248, in main
    process.run()
  File "/media/allen/2637acd8-fd84-4e6e-b830-018fc7f8703c/allen/Desktop/video-quality-metrics-master/ffmpeg_process_factory.py", line 129, in run
    subprocess.run(self.__arguments)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by InB4DevOps** [comment]
Did you add additional parameters to ffmpeg_process_factory.py as suggested in the other issue?
if so, please post your changes here.

**Comment by MillingtonAllen** [comment]
The only changes I had made previously was the -tune psnr, which I commented out before encountering the error, and changing to 4K VMAF calculation.  I just deleted my old video-quality-metrics-master folder, downloaded again to make sure latest version, and ran it again and I'm still having the same error message.  Ubuntu 20.10

**Comment by InB4DevOps** [comment]
I could reproduce the problem. 
If you don't want to wait for the Pull Request to be merged, open main.py in a text editor, go to line 239
and replace 
`arguments.crf = crf`

with 

`arguments.crf = str(crf)`

**Comment by CrypticSignal** [comment]
https://github.com/BassThatHertz/video-quality-metrics/commit/516d1bb787fdd078bdf9de5298c2a4831822c55e closes this issue.
