### ISSUE TITLE
Filename issues [Brackets]

### ISSUE THREAD

**Issue by MillingtonAllen** [BassThatHertz/video-quality-metrics#27]
More filename issues, this time on [brackets]

Ubuntu 20.10

Desktop/video-quality-metrics-master$ python3 main.py -ovp ./\[stuff\].mkv  --interval 60 --clip-length 5 -e x265 --preset medium slow slower veryslow    

[AVFilterGraph @ 0x5b9e880] Unable to parse graph description substring: ".mkv)/Presets comparison at CRF 23/Raw JSON Data/medium.json:log_fmt=json"
Error initializing complex filters.
Invalid argument
Done!
Traceback (most recent call last):
  File "main.py", line 367, in <module>
    main()
  File "main.py", line 270, in main
    create_table_plot_metrics(json_file_path, args, decimal_places, data_for_current_row, graph_filename,
  File "/media/allen/2637acd8-fd84-4e6e-b830-018fc7f8703c/allen/Desktop/video-quality-metrics-master/save_metrics.py", line 12, in create_table_plot_metrics
    with open(json_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '([stuff].mkv)/Presets comparison at CRF 23/Raw JSON Data/medium.json'

It runs fine if I rename the video file to stuff.mkv

**Comment by MillingtonAllen** [comment]
For the above command I forgot about the escape character.  It might be acceptable to enter it without the escape character as it appears to run the same either way, but tab-autocomplete prefers it with the escape character.   It runs into the same error.  

python3 main.py -ovp ./\[stuff\].mkv --interval 60 --clip-length 5 -e x265 --preset medium slow slower veryslow

Computing the VMAF...
[AVFilterGraph @ 0x5f12980] Unable to parse graph description substring: ".mkv)/Presets comparison at CRF 23/Raw JSON Data/medium.json:log_fmt=json"
Error initializing complex filters.
Invalid argument
Done!
Traceback (most recent call last):
  File "main.py", line 367, in <module>
    main()
  File "main.py", line 270, in main
    create_table_plot_metrics(json_file_path, args, decimal_places, data_for_current_row, graph_filename,
  File "/media/allen/2637acd8-fd84-4e6e-b830-018fc7f8703c/allen/Desktop/video-quality-metrics-master/save_metrics.py", line 12, in create_table_plot_metrics
    with open(json_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '([stuff].mkv)/Presets comparison at CRF 23/Raw JSON Data/medium.json'

**Comment by CrypticSignal** [comment]
It seems like the libvmaf's `log_path` option also requires square brackets to be escaped. Please confirm whether commit https://github.com/BassThatHertz/video-quality-metrics/commit/9d93ac799903e2d229995b45841b39f5347e3525 eliminates this issue.

**Comment by MillingtonAllen** [comment]
As of the last update, the ovp parameter seems to work with and without [ ] being escaped in terminal as well as string input.
