### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by polarathene** [BassThatHertz/video-quality-metrics#39]
Following your README, I ran the following and ran into this failure:

```
python main.py -ntm -ovp /tmp/video/a.mp4 -tvp /tmp/video/b.mkv -o test -psnr -ssim

Traceback (most recent call last):
  File "/tmp/video-quality-metrics-master/main.py", line 9, in <module>
    from arguments_validator import ArgumentsValidator
  File "/tmp/video-quality-metrics-master/arguments_validator.py", line 3, in <module>
    from utils import is_list
  File "/tmp/video-quality-metrics-master/utils.py", line 11, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

A quick search revealed that's a package used for displaying a progress bar, so `pip install tqdm` resolved that. Probably should be added to `requirements.txt`?

**Comment by CrypticSignal** [comment]
Correct, [tqdm](https://github.com/tqdm/tqdm is a dependecy. I have now added it to `requirements.txt`.

**Comment by CrypticSignal** [comment]
Yes, [tqdm](https://github.com/tqdm/tqdm) is a dependency. I have now added it to `requirements.txt`.
