### ISSUE TITLE
Deprecated calls to libvmaf

### ISSUE THREAD

**Issue by polarathene** [BassThatHertz/video-quality-metrics#40]
When trying out the project to compare a transcode to an original source, the following warnings were repeated 4 times before the progress bar showed:

```
[libvmaf @ 0x557882dceec0] The "model_path" option is deprecated: use model='path=...'.
[libvmaf @ 0x557882dceec0] The "phone_model" option is deprecated: use model='enable_transform=true'.
[libvmaf @ 0x557882dceec0] The "psnr" option is deprecated: use feature='name=psnr'.
[libvmaf @ 0x557882dceec0] The "ssim" option is deprecated: use feature='name=ssim'.
```

Processing completed (almost?), but failed at the end with the following:

```
100%|█████████████████████████████████████████████████████████████████████████████████████████▋| 317/318 [00:26<00:00, 12.15 frames/s]
Done!
Traceback (most recent call last):
  File "/tmp/video-quality-metrics-master/main.py", line 327, in <module>
    get_metrics_save_table(
  File "/tmp/video-quality-metrics-master/metrics.py", line 55, in get_metrics_save_table
    ssim_scores = [ssim["metrics"]["ssim"] for ssim in file_contents["frames"]]
  File "/tmp/video-quality-metrics-master/metrics.py", line 55, in <listcomp>
    ssim_scores = [ssim["metrics"]["ssim"] for ssim in file_contents["frames"]]
KeyError: 'ssim'
```

**Comment by CrypticSignal** [comment]
Some changes have been made to libvmaf since I last worked on this project. I have just pushed a couple of commits that will fix the `KeyError` and VQM no longer uses deprecated options.

Please confirm whether everything is okay after pulling the latest code.

**Comment by polarathene** [comment]
> Please confirm whether everything is okay after pulling the latest code.

~~I will test after an encode finishes, looking over your commits I think [your PSNR update](https://github.com/CrypticSignal/video-quality-metrics/commit/6c1f273bb248e882bfd631b288691b59fd43b1cc) will not provide any metric though?~~ (**EDIT:** Nevermind, my lack of python skill didn't pickup on the line that filters metrics with `psnr` in the name, not an exact match :+1: )

I had looked into this issue earlier also [for another project I tried](https://github.com/JNoDuq/videobench/issues/39) and forgot to share similar findings here, after I got that project working. Thanks for being so quick to address this, it's really appreciated! :grinning: 

Regarding `ssim`, I don't see `float_ssim` as a feature listed in the [ffmpeg vmaf docs](https://ffmpeg.org/ffmpeg-filters.html#libvmaf), but there is `ssim` and `ms_ssim`.

In the VideoBench project, I noticed that PSNR metric was changed from a single value to individual components of [YCbCr colorspace](https://en.wikipedia.org/wiki/YCbCr), I'm not sure how that differs from the [ffmpeg psnr stats feature](https://ffmpeg.org/ffmpeg-filters.html#toc-psnr) that seems like it can still produce a single value?

---

**UPDATE:** It seems `-psnr` has produced the same chart as `-ssim`.. `Table.txt` lists the same values for the two metrics but the JSON frame data has nothing for PSNR metrics..?

https://github.com/CrypticSignal/video-quality-metrics/blob/fa2ec61f4b36e815b4c906f89afd4e18a459157a/metrics.py#L80-L88

Presumably the `metric_name` variable isn't cleared and is re-used with the earlier `ssim` value last used?

**Comment by polarathene** [comment]
I think you are taking the first `psnr` metric found, which in my test seems to be `psnr_cr`, however `psnr_y` ([luma](https://en.wikipedia.org/wiki/Luma_(video)) channel) is [apparently the most useful of the components](https://www.mathworks.com/help/vision/ref/psnr.html) if you only use one of those. I don't know how to make use of all the components or if that makes sense.

**Comment by polarathene** [comment]
I noticed that your arg building for libvmaf is overriding prior args (model and feature), I resolved this with my limited python skills :)

```python
    n_subsample = "1" if not args.subsample else args.subsample

    model_params = [
        f"path={model_file_path}",
        "enable_transform=true" if args.phone_model else ""
    ]
    model_string = f"model='{'|'.join(filter(None, model_params))}'"

    features = [
        "name=psnr" if args.calculate_psnr else "",
        "name=float_ssim" if args.calculate_ssim else ""
    ]
    feature_string = f":feature='{'|'.join(filter(None, features))}'"

    vmaf_options = f"""
    {model_string}:log_fmt=json:log_path='{json_file_path}':n_subsample={n_subsample}:n_threads={args.n_threads}{feature_string}
    """
```

for:

https://github.com/CrypticSignal/video-quality-metrics/blob/fa2ec61f4b36e815b4c906f89afd4e18a459157a/libvmaf.py#L25-L33

**Comment by CrypticSignal** [comment]
> Regarding ssim, I don't see float_ssim as a feature listed in the [ffmpeg vmaf docs](https://ffmpeg.org/ffmpeg-filters.html#libvmaf), but there is ssim and ms_ssim.

The reason I specified `float_ssim` as the feature name is because I get the following error if I set the feature name to `ssim`:
"[Parsed_libvmaf_2 @ 0x7f8b12e13ac0] problem during vmaf_use_feature: ssim"

`float_ssim` is definitely an available metric, here is the metric data for one of the frames during the testing I did:
```
"metrics": {
  "integer_motion2": 0.000000,
  "integer_motion": 0.000000,
  "integer_adm2": 0.993905,
  "integer_adm_scale0": 0.987449,
  "integer_adm_scale1": 0.987860,
  "integer_adm_scale2": 0.993810,
  "integer_adm_scale3": 0.997650,
  "float_ssim": 0.997231,
  "integer_vif_scale0": 0.793798,
  "integer_vif_scale1": 0.985087,
  "integer_vif_scale2": 0.992539,
  "integer_vif_scale3": 0.995357,
  "vmaf": 95.318506
}
```
> I noticed that your arg building for libvmaf is overriding prior args (model and feature)

I'm not sure what you mean by this.
> I think you are taking the first psnr metric found

It will take the last PSNR metric it finds as the for-loop iterates over each metric and redefines `metric_name` whenever there is a metric with "psnr" in its name. I could hardcore `psnr_y` as the metric to use, but from the quick testing I just did, the JSON file produced does not contain a PSNR metric and I'm not sure why this is.

It's nearly 12am for me so I will look into this tomorrow.

**Comment by polarathene** [comment]
> I'm not sure what you mean by this.

You were generating params like this:

```
model=path=vmaf_models/vmaf_v0.6.1.json:log_fmt=json:log_path=results/Metrics of each frame.json:n_subsample=1:n_threads=4:feature='name=psnr':feature='name=ssim'
```

This resulted in the `psnr` feature being dropped in favor of the newer `ssim` feature declaration. [FFMpeg VMAF docs](https://ffmpeg.org/ffmpeg-filters.html#libvmaf) state you should handle multiple values with a `|` delimiter instead, as I've shown above.

With that change, the data json you write out will actually have both metrics.

> It will take the last PSNR metric it finds as the for-loop iterates over each metric and redefines `metric_name` whenever there is a metric with "psnr" in its name.

Ah ok, either way, `psnr_y` is more useful out of the 3 components AFAIK. In some languages the field from iterating an object isn't always stable IIRC, so I wasn't sure how that played out with python :sweat_smile: 

I think preferring `psnr_y` for now is the best route, if not I'm sure a user will raise an issue to detail why :)

> the JSON file produced does not contain a PSNR metric and I'm not sure why this is.

Yup, that was what I was pointing out earlier, hope it makes sense now. (_This is a little difficult to respond to with all the edits you're making as I respond_ :laughing: )

> It's nearly 12am for me so I will look into this tomorrow.

No worries, get some rest! ~~I can look into PRing the proposed changes if you like?~~ ([done!](https://github.com/CrypticSignal/video-quality-metrics/pull/41))

---

I tried the FFMPEG VMAF documented options `ssim` and `ms_ssim` neither worked as features though, ~~so `float_ssim` is fine. Not too fussed about that and I don't have the motivation to investigate that further.~~

**UPDATE:**

Accepted features are detailed for VMAF [here](https://github.com/Netflix/vmaf/issues/787#issuecomment-761255513) where the names may depend on a compile option for ffmpeg, such as `ssim` becoming `float_ssim`, this also makes `ms_sssim` available by adding the `float_` prefix.

[A related PR](https://github.com/Netflix/vmaf/pull/806/files) also seems to indicate that `psnr_y` is associated to the previous version single `psnr` value.
