### ISSUE TITLE
Bitrate in table.txt

### ISSUE THREAD

**Issue by InB4DevOps** [BassThatHertz/video-quality-metrics#8]
Hey @BassThatHertz 
how about we take the avg bitrate that ffmpeg outputs at the end of an encode and add that to the table?
Just wanted to make sure that was something you'd like before I'd dive into it..

**Comment by CrypticSignal** [comment]
I have just pushed an update. One of the changes that I've made is splitting the codebase into two files, to make it a little more manageable. You should pull the changes that I've made before trying to add the average bitrate to the table. It would be a nice addition 👍

**Comment by InB4DevOps** [comment]
Ok. Nice update!
Will look into adding bitrate to the table.

**Comment by CrypticSignal** [comment]
I appreciate your active involvement. Good luck! :)

**Comment by InB4DevOps** [comment]
You're very welcome!
I'm glad I finally found an open source project I can contribute to :)

**Comment by InB4DevOps** [comment]
I have a few more ideas to  bring more modes to VQM but let's keep it one at a time. :)

**Comment by CrypticSignal** [comment]
Thank you for your pull request which adds the bitrate of each transcode to Table.txt, https://github.com/BassThatHertz/video-quality-metrics/commit/b28cc69a1c49b1cb5c0b84f8ceddb527cc6cf2bd closes this "issue".
